version: "3.8"
services:
  holder:
    build: ./BE/holder
    image: edac99/image-repo:holder-1.0.0
    ports:
      - "8081:8081"

  issuer:
    build: ./BE/issuer
    image: edac99/image-repo:issuer-1.0.0
    ports:
      - "8082:8082"

  verifier:
    build: ./BE/verifier
    image: edac99/image-repo:verifier-1.0.0
    ports:
      - "8083:8083"

  service:
    build: ./BE/service
    image: edac99/image-repo:service-1.0.0
    ports:
      - "4000:4000"
