version: "3.8"
services:
  holder:
    build: ./BE/holder
    image: holder
    ports:
      - 8081:8081
    volumes:
      - ./BE/holder:/usr/src/app

  issuer:
    build: ./BE/issuer
    image: issuer
    ports:
      - 8082:8082
    volumes:
      - ./BE/issuer:/usr/src/app
      - /usr/src/app/node_modules

  verifier:
    build: ./BE/verifier
    image: verifier
    ports:
      - 8083:8083
    volumes:
      - ./BE/verifier:/usr/src/app
      - /usr/src/app/node_modules

  service:
    build: ./BE/service
    image: service
    ports:
      - 4000:4000
    depends_on:
      - mysql
    volumes:
      - ./BE/service:/usr/src/app

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: db
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
