[package]
name = "test_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = "0.1"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]

# [features]
# default = ["console_error_panic_hook"]
