name: Auto Test (Service API only)

on:
  pull_request:
    branches: [main, dev]

jobs:
  auto-test:
    name: Run test codes
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Node 20.11
        uses: actions/setup-node@v2
        with:
          node-version: "20.11"

      - name: Install dependencies
        run: cd ./BE/holder && npm i

      - name: Run test
        run: cd ./BE/holder && npm run test
