name: Docker 배포

on:
  pull_request:
    branches:
      - dev

jobs:
  job1:
    name: Docker 환경 빌드
    runs-on: ubuntu-20.04

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: DockerHub 로그인
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
